In [123]:

print("bon2")
a =[1, 2]
print(sum(a))

bon2
3

In [124]:
a = ['foo', 'bar', 'baz', 'qux', 'corge']

while a:
    if len(a) < 3:
        break
    print(a.pop())
print('Done.')

corge
qux
baz
Done.

In [125]:
import random


for j in range(20):
    success = False
    for i in range(4):
       a = random.randint(0,1)
       # print("#1: "+a)
       if a == 1:
        success = True
    print (success)


print(random.uniform(10,20))

True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
False
True
12.141473745193121

En premier lieu un jeu que l’on notera A qui est un simple jeu de pile ou face avec une pièce biaisée (pile avec une probabilité de p=0.49). Le joueur mise un euro et lance la pièce : s’il obtient pile il gagne un euro en plus de récupérer sa mise, sinon il perd sa mise.
Ensuite, un jeu que l’on notera B, qui est un jeu avec deux pièces biaisées. La première pièce donne pile avec une probabilité p1 = 0.09 et la seconde pièce donne pile avec une probabilité p2 = 0.74. Le joueur ne peut miser qu’un euro à la fois ! En revanche, on regarde à chaque lancé son capital (la somme d’argent totale) dont il dispose pour déterminer quelle pièce lancer : si le capital est un multiple de 3, on lance la pièce numéro une, sinon on lance la seconde pièce. Comme dans le jeu A, le joueur remporte sa mise plus un euro supplémentaire si la pièce choisie tombe sur pile, sinon il perd sa mise.

In [126]:


resultatsJeu1 = []
resultatsJeu2 = []

for j in range(10000):
    capital = 1000
    for i in range(200):
        if random.binomialvariate(1, 0.49)==1:
            capital+=1
        else:
            capital-=1

    resultatsJeu1.append(capital)

    capital = 1000
    for i in range(200):
        if (i%3 == 0):
            if random.binomialvariate(1, 0.09)==1:
                capital+=1
            else:
                capital-=1
        else:
            if random.binomialvariate(1, 0.74)==1:
                capital+=1
            else:
                capital-=1
    resultatsJeu2.append(capital)

print("Jeu1: "+ str(sum(resultatsJeu1)/len(resultatsJeu1)))
print("Jeu2: "+ str(sum(resultatsJeu2)/len(resultatsJeu2)))

AttributeError: module 'random' has no attribute 'binomialvariate'

In [ ]:
print(3%3)

0

In [ ]:
import numpy as np

In [ ]:
un = np.ones((3,3,3))
display(un)
print(un.sum())
un[1,1,1]

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

27.0

np.float64(1.0)

In [ ]:
a = np.linspace(5, 10, 11)
display(a)
print(a[-3:-1])
print(a[0])

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

[9.  9.5]
5.0

In [ ]:
a[a % 2 == 0]

array([ 6.,  8., 10.])

In [ ]:
b = np.array([[[1, 2],[4, 5]],
        [[6, 7],[8, 9]],
        [[10, 11],[12, 13]]])

b.shape
b[2, :, :]

array([[10, 11],
       [12, 13]])

# Pandas Cours

In [ ]:
# chargement du fichier
import pandas as pd
data = pd.read_csv("clients.csv")
data

     identifiant                            email                nom genre
0              0        LaurentDagenais@rhyta.com   Laurent Dagenais     M
1              1            GuyMarois@fleckens.hu         Guy Marois     M
2              2        BeaufortLesage@einrot.com    Beaufort Lesage     M
3              3        RussellDurand@armyspy.com     Russell Durand     M
4              4             AlexisRiel@rhyta.com        Alexis Riel     M
..           ...                              ...                ...   ...
223          223  ClaudeDandonneau@jourrapide.com  Claude Dandonneau     F
224          224    ApollineMichaud@superrito.com   Apolline Michaud     F
225          225       PascalineBeaudry@rhyta.com  Pascaline Beaudry     F
226          226     FleurCaouette@jourrapide.com     Fleur Caouette     F
227          227      FrancisMasse@jourrapide.com      Francis Masse     M

[228 rows x 4 columns]

In [ ]:
notes = pd.read_csv('notes.csv')

In [ ]:
notes.tail()

                   nom          matiere  note
79    Agrican Foucault  Physique/Chimie     9
80  Prunella Josseaume  Physique/Chimie     6
81      Yseult Charest  Physique/Chimie    16
82      Dorothee Aupry  Physique/Chimie    17
83       Amaury Reault  Physique/Chimie     8

In [ ]:
from operator import index


notes.loc[notes['matiere'] == 'Mathématiques']['note'].mean()
notes.groupby('matiere')['note'].mean()
classt = notes.groupby('nom')['note'].mean()
classt
#classt.shape
classt.sort_values(inplace=True)
classt.loc[classt < 10]
#classt.reset_index(drop=True)
#classt
notes.loc[((notes['matiere'] == 'Mathématiques') | (notes['matiere'] == 'Physique/Chimie')) & (notes['note'] >= 15), 'nom']

22         Guy Marois
23    Beaufort Lesage
28     Agramant Pepin
30    Theodore Clavet
31     Byron Lefebvre
32       Florus Devoe
65    Beaufort Lesage
68      Leon Lapresse
70     Agramant Pepin
74       Florus Devoe
78    Agate Grandbois
81     Yseult Charest
82     Dorothee Aupry
Name: nom, dtype: object

Quizz merge

In [129]:
produits = pd.read_csv('csv_P2_quizz/produits.csv')
commande = pd.read_csv('csv_P2_quizz/commande.csv')

In [145]:
display(produits.head())
display(commande.head())

pro_cde = pd.merge(produits, commande)
#pro_cde.isna()[pro_cde.isna()['id'] == False]

pro_cde['valeur'] = pro_cde['prix'] * pro_cde['nombre']
pro_cde
CA = pro_cde.groupby('id')['valeur'].sum()
display(CA.sort_values())
ventes = pro_cde.groupby('id')['nombre'].sum()

   id  prix
0   0  24.8
1   1  13.1
2   2  23.7
3   3  16.0
4   4  19.0

   id  nombre
0  70       2
1  41       4
2  72       2
3  92       8
4  73       1

id
58     142.8
92     148.0
63     187.0
29     226.8
62     260.0
       ...
27    2107.0
19    2117.2
30    2216.1
65    2524.8
8     2636.8
Name: valeur, Length: 100, dtype: float64